/*
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 */
#ifndef _NETX4000_DDR_H_
#define _NETX4000_DDR_H_

#include <mach/netx4000_regs.h>

/* DDR Phy registers */
#define DDRPHY_FUNCCTRL				(NETX4000_DDRPHY_BASE + 0x00)
#define Adr_NX4000_DDR_PHY_DDR_PHY_FUNCCTRL	DDRPHY_FUNCCTRL
#define DDRPHY_DLLCTRL				(NETX4000_DDRPHY_BASE + 0x04)
#define DDRPHY_ZQCALCTRL			(NETX4000_DDRPHY_BASE + 0x08)
#define DDRPHY_ZQODTCTRL			(NETX4000_DDRPHY_BASE + 0x0C)
#define DDRPHY_RDCTRL				(NETX4000_DDRPHY_BASE + 0x10)
#define DDRPHY_RDTMG				(NETX4000_DDRPHY_BASE + 0x14)
#define DDRPHY_FIFOINIT				(NETX4000_DDRPHY_BASE + 0x18)
#define DDRPHY_OUTCTRL				(NETX4000_DDRPHY_BASE + 0x1C)

#define DDRPHY_FUNCCTRL_IFSEL_SHIFT		(8)
#define SRT_NX4000_DDR_PHY_FUNCCTRL_IFSEL	DDRPHY_FUNCCTRL_IFSEL_SHIFT
#define DDRPHY_FUNCCTRL_IFSEL_MASK		(3 << DDRPHY_FUNCCTRL_IFSEL_SHIFT)
#define DDRPHY_FUNCCTRL_FUNCRSTB_SHIFT		(0)
#define DDRPHY_FUNCCTRL_FUNCRSTB_MASK		(1 << DDRPHY_FUNCCTRL_FUNCRSTB_SHIFT)
#define MSK_NX4000_DDR_PHY_FUNCCTRL_FUNCRSTB	DDRPHY_FUNCCTRL_FUNCRSTB_MASK

#define DDRPHY_DLLCTRL_MDLLOCK_SHIFT		(25)
#define DDRPHY_DLLCTRL_MDLLOCK_MASK		(1 << DDRPHY_DLLCTRL_MDLLOCK_SHIFT)
#define DDRPHY_DLLCTRL_MSATFG_SHIFT		(24)
#define DDRPHY_DLLCTRL_MSATFG_MASK		(1 << DDRPHY_DLLCTRL_MSATFG_SHIFT)
#define DDRPHY_DLLCTRL_MDACNTM_SHIFT		(22)
#define DDRPHY_DLLCTRL_MDACNTM_MASK		(1 << DDRPHY_DLLCTRL_MDACNTM_SHIFT)
#define DDRPHY_DLLCTRL_SDLYCTRL_SHIFT		(21)
#define DDRPHY_DLLCTRL_SDLYCTRL_MASK		(1 << DDRPHY_DLLCTRL_SDLYCTRL_SHIFT)
#define DDRPHY_DLLCTRL_DACNTUPD_SHIFT		(20)
#define DDRPHY_DLLCTRL_DACNTUPD_MASK		(1 << DDRPHY_DLLCTRL_DACNTUPD_SHIFT)
#define DDRPHY_DLLCTRL_MDACNT_SHIFT		(8)
#define DDRPHY_DLLCTRL_MDACNT_MASK		(0x3FF << DDRPHY_DLLCTRL_MDACNT_SHIFT)
#define DDRPHY_DLLCTRL_HSLMODE_SHIFT		(5)
#define DDRPHY_DLLCTRL_HSLMODE_MASK		(1 << DDRPHY_DLLCTRL_HSLMODE_SHIFT)
#define DDRPHY_DLLCTRL_MSATMODE_SHIFT		(4)
#define DDRPHY_DLLCTRL_MSATMODE_MASK		(1 << DDRPHY_DLLCTRL_MSATMODE_SHIFT)
#define DDRPHY_DLLCTRL_DDMODE_SHIFT		(3)
#define DDRPHY_DLLCTRL_DDMODE_MASK		(1 << DDRPHY_DLLCTRL_DDMODE_SHIFT)
#define DDRPHY_DLLCTRL_MFSL_SHIFT		(1)
#define SRT_NX4000_DDR_PHY_DLLCTRL_MFSL		DDRPHY_DLLCTRL_MFSL_SHIFT
#define DDRPHY_DLLCTRL_MFSL_MASK		(3 << DDRPHY_DLLCTRL_MFSL_SHIFT)
#define DDRPHY_DLLCTRL_MDLLSTBY_SHIFT		(0)
#define DDRPHY_DLLCTRL_MDLLSTBY_MASK		(1 << DDRPHY_DLLCTRL_MDLLSTBY_SHIFT)

#define DDRPHY_ZQCALCTRL_ZQCALRUN_SHIFT		(31)
#define DDRPHY_ZQCALCTRL_ZQCALRUN_MASK		(1 << DDRPHY_ZQCALCTRL_ZQCALRUN_SHIFT)
#define DDRPHY_ZQCALCTRL_ZQCALEND_SHIFT		(30)
#define DDRPHY_ZQCALCTRL_ZQCALEND_MASK		(1 << DDRPHY_ZQCALCTRL_ZQCALEND_SHIFT)
#define MSK_NX4000_DDR_PHY_ZQCALCTRL_ZQCALEND	DDRPHY_ZQCALCTRL_ZQCALEND_MASK
#define DDRPHY_ZQCALCTRL_ZQCALGAP_SHIFT		(29)
#define DDRPHY_ZQCALCTRL_ZQCALGAP_MASK		(1 << DDRPHY_ZQCALCTRL_ZQCALGAP_SHIFT)
#define DDRPHY_ZQCALCTRL_ZQCALPC_SHIFT		(26)
#define DDRPHY_ZQCALCTRL_ZQCALPC_MASK		(0x7 << DDRPHY_ZQCALCTRL_ZQCALPC_SHIFT)
#define DDRPHY_ZQCALCTRL_ZQCALPF_SHIFT		(22)
#define DDRPHY_ZQCALCTRL_ZQCALPF_MASK		(0xF << DDRPHY_ZQCALCTRL_ZQCALPF_SHIFT)
#define DDRPHY_ZQCALCTRL_ZQCALNC_SHIFT		(19)
#define DDRPHY_ZQCALCTRL_ZQCALNC_MASK		(7 << DDRPHY_ZQCALCTRL_ZQCALNC_SHIFT)
#define DDRPHY_ZQCALCTRL_ZQCALNF_SHIFT		(15)
#define DDRPHY_ZQCALCTRL_ZQCALNF_MASK		(0xF << DDRPHY_ZQCALCTRL_ZQCALNF_SHIFT)
#define DDRPHY_ZQCALCTRL_ZQCALINIT_SHIFT	(14)
#define DDRPHY_ZQCALCTRL_ZQCALINIT_MASK		(1 << DDRPHY_ZQCALCTRL_ZQCALINIT_SHIFT)
#define DDRPHY_ZQCALCTRL_ZQCALUPD_SHIFT		(10)
#define SRT_NX4000_DDR_PHY_ZQCALCTRL_ZQCALUPD	DDRPHY_ZQCALCTRL_ZQCALUPD_SHIFT
#define DDRPHY_ZQCALCTRL_ZQCALUPD_MASK		(3 << DDRPHY_ZQCALCTRL_ZQCALUPD_SHIFT)
#define DDRPHY_ZQCALCTRL_ZQCALFREQ_SHIFT	(8)
#define SRT_NX4000_DDR_PHY_ZQCALCTRL_ZQCALFREQ	DDRPHY_ZQCALCTRL_ZQCALFREQ_SHIFT
#define DDRPHY_ZQCALCTRL_ZQCALFREQ_MASK		(3 << DDRPHY_ZQCALCTRL_ZQCALFREQ_SHIFT)
#define DDRPHY_ZQCALCTRL_ZQCALITVL_SHIFT	(4)
#define SRT_NX4000_DDR_PHY_ZQCALCTRL_ZQCALITVL	DDRPHY_ZQCALCTRL_ZQCALITVL_SHIFT
#define DDRPHY_ZQCALCTRL_ZQCALITVL_MASK		(0xF << DDRPHY_ZQCALCTRL_ZQCALITVL_SHIFT)
#define DDRPHY_ZQCALCTRL_ZQCALMODE_SHIFT	(2)
#define DDRPHY_ZQCALCTRL_ZQCALMODE_MASK		(1 << DDRPHY_ZQCALCTRL_ZQCALMODE_SHIFT)
#define MSK_NX4000_DDR_PHY_ZQCALCTRL_ZQCALMODE	DDRPHY_ZQCALCTRL_ZQCALMODE_MASK
#define DDRPHY_ZQCALCTRL_ZQCALSTRV_SHIFT	(1)
#define DDRPHY_ZQCALCTRL_ZQCALSTRV_MASK		(1 << DDRPHY_ZQCALCTRL_ZQCALSTRV_SHIFT)
#define MSK_NX4000_DDR_PHY_ZQCALCTRL_ZQCALSTRV	DDRPHY_ZQCALCTRL_ZQCALSTRV_MASK
#define DDRPHY_ZQCALCTRL_ZQCALRSTB_SHIFT	(0)
#define DDRPHY_ZQCALCTRL_ZQCALRSTB_MASK		(1 << DDRPHY_ZQCALCTRL_ZQCALRSTB_SHIFT)
#define MSK_NX4000_DDR_PHY_ZQCALCTRL_ZQCALRSTB	DDRPHY_ZQCALCTRL_ZQCALRSTB_MASK

#define DDRPHY_ZQODTCTRL_CAPHASE_SHIFT		(30)
#define SRT_NX4000_DDR_PHY_ZQODTCTRL_CAPHASE	DDRPHY_ZQODTCTRL_CAPHASE_SHIFT
#define DDRPHY_ZQODTCTRL_CAPHASE_MASK		(3 << DDRPHY_ZQODTCTRL_CAPHASE_SHIFT)
#define DDRPHY_ZQODTCTRL_WRFIFOEN_SHIFT		(29)
#define DDRPHY_ZQODTCTRL_WRFIFOEN_MASK		(1 << DDRPHY_ZQODTCTRL_WRFIFOEN_SHIFT)
#define MSK_NX4000_DDR_PHY_ZQODTCTRL_WRFIFOEN	DDRPHY_ZQODTCTRL_WRFIFOEN_MASK
#define DDRPHY_ZQODTCTRL_FIFORPINIT_SHIFT	(27)
#define SRT_NX4000_DDR_PHY_ZQODTCTRL_FIFORPINIT	DDRPHY_ZQODTCTRL_FIFORPINIT_SHIFT
#define DDRPHY_ZQODTCTRL_FIFORPINIT_MASK	(3 << DDRPHY_ZQODTCTRL_FIFORPINIT_SHIFT)
#define DDRPHY_ZQODTCTRL_ZQDATA_SHIFT		(23)
#define SRT_NX4000_DDR_PHY_ZQODTCTRL_ZQDATA	DDRPHY_ZQODTCTRL_ZQDATA_SHIFT
#define DDRPHY_ZQODTCTRL_ZQDATA_MASK		(0xF << DDRPHY_ZQODTCTRL_ZQDATA_SHIFT)
#define DDRPHY_ZQODTCTRL_ZQCK_SHIFT		(19)
#define SRT_NX4000_DDR_PHY_ZQODTCTRL_ZQCK	DDRPHY_ZQODTCTRL_ZQCK_SHIFT
#define DDRPHY_ZQODTCTRL_ZQCK_MASK		(0xF << DDRPHY_ZQODTCTRL_ZQCK_SHIFT)
#define DDRPHY_ZQODTCTRL_ZQCMDAD_SHIFT		(15)
#define SRT_NX4000_DDR_PHY_ZQODTCTRL_ZQCMDAD	DDRPHY_ZQODTCTRL_ZQCMDAD_SHIFT
#define DDRPHY_ZQODTCTRL_ZQCMDAD_MASK		(0xF << DDRPHY_ZQODTCTRL_ZQCMDAD_SHIFT)
#define DDRPHY_ZQODTCTRL_SRDQ_SHIFT		(12)
#define DDRPHY_ZQODTCTRL_SRDQ_MASK		(3 << DDRPHY_ZQODTCTRL_SRDQ_SHIFT)
#define DDRPHY_ZQODTCTRL_SRCK_SHIFT		(10)
#define DDRPHY_ZQODTCTRL_SRCK_MASK		(3 << DDRPHY_ZQODTCTRL_SRCK_SHIFT)
#define DDRPHY_ZQODTCTRL_SRCMDAD_SHIFT		(8)
#define DDRPHY_ZQODTCTRL_SRCMDAD_MASK		(3 << DDRPHY_ZQODTCTRL_SRCMDAD_SHIFT)
#define DDRPHY_ZQODTCTRL_PHYODT_SHIFT		(5)
#define SRT_NX4000_DDR_PHY_ZQODTCTRL_PHYODT	DDRPHY_ZQODTCTRL_PHYODT_SHIFT
#define DDRPHY_ZQODTCTRL_PHYODT_MASK		(3 << DDRPHY_ZQODTCTRL_PHYODT_SHIFT)
#define DDRPHY_ZQODTCTRL_PHYODTEN_SHIFT		(4)
#define DDRPHY_ZQODTCTRL_PHYODTEN_MASK		(1 << DDRPHY_ZQODTCTRL_PHYODTEN_SHIFT)
#define MSK_NX4000_DDR_PHY_ZQODTCTRL_PHYODTEN	DDRPHY_ZQODTCTRL_PHYODTEN_MASK
#define DDRPHY_ZQODTCTRL_DNVEN_SHIFT		(3)
#define DDRPHY_ZQODTCTRL_DNVEN_MASK		(1 << DDRPHY_ZQODTCTRL_DNVEN_SHIFT)
#define DDRPHY_ZQODTCTRL_DRAMIF_SHIFT		(0)
#define SRT_NX4000_DDR_PHY_ZQODTCTRL_DRAMIF	DDRPHY_ZQODTCTRL_DRAMIF_SHIFT
#define DDRPHY_ZQODTCTRL_DRAMIF_MASK		(3 << DDRPHY_ZQODTCTRL_DRAMIF_SHIFT)

#define DDRPHY_RDCTRL_PHYODTONT_SHIFT		(28)
#define SRT_NX4000_DDR_PHY_RDCTRL_PHYODTONT	DDRPHY_RDCTRL_PHYODTONT_SHIFT
#define DDRPHY_RDCTRL_PHYODTONT_MASK		(0xF << DDRPHY_RDCTRL_PHYODTONT_SHIFT)
#define DDRPHY_RDCTRL_PHYODTOFT_SHIFT		(24)
#define SRT_NX4000_DDR_PHY_RDCTRL_PHYODTOFT	(DDRPHY_RDCTRL_PHYODTOFT_SHIFT)
#define DDRPHY_RDCTRL_PHYODTOFT_MASK		(0xF << DDRPHY_RDCTRL_PHYODTOFT_SHIFT)
#define DDRPHY_RDCTRL_PDQODTONT_SHIFT		(20)
#define SRT_NX4000_DDR_PHY_RDCTRL_PDQODTONT	DDRPHY_RDCTRL_PDQODTONT_SHIFT
#define DDRPHY_RDCTRL_PDQODTONT_MASK		(0xF << DDRPHY_RDCTRL_PDQODTONT_SHIFT)
#define DDRPHY_RDCTRL_PDQODTOFT_SHIFT		(16)
#define SRT_NX4000_DDR_PHY_RDCTRL_PDQODTOFT	DDRPHY_RDCTRL_PDQODTOFT_SHIFT
#define DDRPHY_RDCTRL_PDQODTOFT_MASK		(0xF << DDRPHY_RDCTRL_PDQODTOFT_SHIFT)
#define DDRPHY_RDCTRL_PHYBENONT_SHIFT		(12)
#define SRT_NX4000_DDR_PHY_RDCTRL_PHYBENONT	DDRPHY_RDCTRL_PHYBENONT_SHIFT
#define DDRPHY_RDCTRL_PHYBENONT_MASK		(0xF << DDRPHY_RDCTRL_PHYBENONT_SHIFT)
#define DDRPHY_RDCTRL_PHYBENOFT_SHIFT		(8)
#define SRT_NX4000_DDR_PHY_RDCTRL_PHYBENOFT	DDRPHY_RDCTRL_PHYBENOFT_SHIFT
#define DDRPHY_RDCTRL_PHYBENOFT_MASK		(0xF << DDRPHY_RDCTRL_PHYBENOFT_SHIFT)
#define DDRPHY_RDCTRL_PHYIENONT_SHIFT		(4)
#define SRT_NX4000_DDR_PHY_RDCTRL_PHYIENONT	DDRPHY_RDCTRL_PHYIENONT_SHIFT
#define DDRPHY_RDCTRL_PHYIENONT_MASK		(0xF << DDRPHY_RDCTRL_PHYIENONT_SHIFT)
#define DDRPHY_RDCTRL_PHYIENOFT_SHIFT		(0)
#define SRT_NX4000_DDR_PHY_RDCTRL_PHYIENOFT	DDRPHY_RDCTRL_PHYIENOFT_SHIFT
#define DDRPHY_RDCTRL_PHYIENOFT_MASK		(0xF << DDRPHY_RDCTRL_PHYIENOFT_SHIFT)

#define DDRPHY_RDTMG_MASKSFT_SHIFT		(9)
#define DDRPHY_RDTMG_MASKSFT_MASK		(1 << DDRPHY_RDTMG_MASKSFT_SHIFT)
#define DDRPHY_RDTMG_RDMODE_SHIFT		(8)
#define DDRPHY_RDTMG_RDMODE_MASK		(1 << DDRPHY_RDTMG_RDMODE_SHIFT)
#define MSK_NX4000_DDR_PHY_RDTMG_RDMODE		DDRPHY_RDTMG_RDMODE_MASK
#define DDRPHY_RDTMG_RDENVALID_SHIFT		(4)
#define SRT_NX4000_DDR_PHY_RDTMG_RDENVALID	DDRPHY_RDTMG_RDENVALID_SHIFT
#define DDRPHY_RDTMG_RDENVALID_MASK		(0xF << DDRPHY_RDTMG_RDENVALID_SHIFT)
#define DDRPHY_RDTMG_WDOMODE_SHIFT		(0)
#define SRT_NX4000_DDR_PHY_RDTMG_WDOMODE	DDRPHY_RDTMG_WDOMODE_SHIFT
#define DDRPHY_RDTMG_WDOMODE_MASK		(3 << DDRPHY_RDTMG_WDOMODE_SHIFT)

#define DDRPHY_FIFOINIT_RDPTINITEXE_SHIFT	(8)
#define DDRPHY_FIFOINIT_RDPTINITEXE_MASK	(1 << DDRPHY_FIFOINIT_RDPTINITEXE_SHIFT)
#define MSK_NX4000_DDR_PHY_FIFOINIT_RDPTINITEXE	DDRPHY_FIFOINIT_RDPTINITEXE_MASK
#define DDRPHY_FIFOINIT_WRPTINITEXE_SHIFT	(0)
#define DDRPHY_FIFOINIT_WRPTINITEXE_MASK	(1 << DDRPHY_FIFOINIT_WRPTINITEXE_SHIFT)
#define MSK_NX4000_DDR_PHY_FIFOINIT_WRPTINITEXE	DDRPHY_FIFOINIT_WRPTINITEXE_MASK

#define DDRPHY_OUTCTRL_CKOBUFEN_SHIFT		(26)
#define SRT_NX4000_DDR_PHY_OUTCTRL_CKOBUFEN	DDRPHY_OUTCTRL_CKOBUFEN_SHIFT
#define DDRPHY_OUTCTRL_CKOBUFEN_MASK		(7 << DDRPHY_OUTCTRL_CKOBUFEN_SHIFT)
#define DDRPHY_OUTCTRL_MBL_SHIFT		(24)
#define SRT_NX4000_DDR_PHY_OUTCTRL_MBL		DDRPHY_OUTCTRL_MBL_SHIFT
#define DDRPHY_OUTCTRL_MBL_MASK			(3 << DDRPHY_OUTCTRL_MBL_SHIFT)
#define DDRPHY_OUTCTRL_MRL_SHIFT		(16)
#define SRT_NX4000_DDR_PHY_OUTCTRL_MRL		DDRPHY_OUTCTRL_MRL_SHIFT
#define DDRPHY_OUTCTRL_MRL_MASK			(0x1F << DDRPHY_OUTCTRL_MRL_SHIFT)
#define DDRPHY_OUTCTRL_MWL_SHIFT		(8)
#define SRT_NX4000_DDR_PHY_OUTCTRL_MWL		DDRPHY_OUTCTRL_MWL_SHIFT
#define DDRPHY_OUTCTRL_MWL_MASK			(0x1F << DDRPHY_OUTCTRL_MWL_SHIFT)
#define DDRPHY_OUTCTRL_RESETBOE_SHIFT		(2)
#define DDRPHY_OUTCTRL_RESETBOE_MASK		(1 << DDRPHY_OUTCTRL_RESETBOE_SHIFT)
#define MSK_NX4000_DDR_PHY_OUTCTRL_RESETBOE	DDRPHY_OUTCTRL_RESETBOE_MASK
#define DDRPHY_OUTCTRL_CKEODTOE_SHIFT		(1)
#define DDRPHY_OUTCTRL_CKEODTOE_MASK		(1 << DDRPHY_OUTCTRL_CKEODTOE_SHIFT)
#define MSK_NX4000_DDR_PHY_OUTCTRL_CKEODTOE	DDRPHY_OUTCTRL_CKEODTOE_MASK
#define DDRPHY_OUTCTRL_ADCMODE_SHIFT		(0)
#define DDRPHY_OUTCTRL_ADCMODE_MASK		(1 << DDRPHY_OUTCTRL_ADCMODE_SHIFT)
#define MSK_NX4000_DDR_PHY_OUTCTRL_ADCMDOE	DDRPHY_OUTCTRL_ADCMODE_MASK

/* DDR memory controller registers */
#define DENALI_CTL(n)			(NETX4000_DDRREGS_BASE + (n) * 4)

#define DENALI_CTL0_VERSION_SHIFT	(16)
#define DENALI_CTL0_VERSION_MASK	(0xFFFF << DENALI_CTL0_VERSION_SHIFT)
#define DENALI_CTL0_DRAM_CLASS_SHIFT	(8)
#define DENALI_CTL0_DRAM_CLASS_MASK	(0xF << DENALI_CTL0_DRAM_CLASS_SHIFT)
#define DENALI_CTL0_START_SHIFT		(0)
#define DENALI_CTL0_START_MASK		(1 << DENALI_CTL0_START_SHIFT)

#define DENALI_CTL1_MAXCS_SHIFT		(16)
#define DENALI_CTL1_MAXCS_MASK		(0x1 << DENALI_CTL1_MAXCS_SHIFT)
#define DENALI_CTL1_MAXCOL_SHIFT	(8)
#define DENALI_CTL1_MAXCOL_MASK		(0xF << DENALI_CTL1_MAXCOL_SHIFT)
#define DENALI_CTL1_MAXROW_SHIFT	(0)
#define DENALI_CTL1_MAXROW_MASK		(0x1F << DENALI_CTL1_MAXROW_SHIFT)

#define DENALI_CTL2_TINIT_SHIFT		(0)
#define DENALI_CTL2_TINIT_MASK		(0xFFFFFF << DENALI_CTL2_TINIT_SHIFT)

#define DENALI_CTL6_TRSTPWRON_SHIFT	(0)
#define DENALI_CTL6_TRSTPWRON_MASK	(0xFFFFFFFF << DENALI_CTL6_TRSTPWRON_SHIFT)

#define DENALI_CTL7_CKEINACTIVE_SHIFT	(0)
#define DENALI_CTL7_CKEINACTIVE_MASK	(0xFFFFFFFF << DENALI_CTL7_CKEINACTIVE_SHIFT)

#define DENALI_CTL8_TCPD_SHIFT		(8)
#define DENALI_CTL8_TCPD_MASK		(0xFFFF << DENALI_CTL8_TCPD_SHIFT)
#define DENALI_CTL8_INITAREF_SHIFT	(0)
#define DENALI_CTL8_INITAREF_MASK	(0xF << DENALI_CTL8_INITAREF_SHIFT)

#define DENALI_CTL9_CASLAT_LIN_SHIFT	(24)
#define DENALI_CTL9_CASLAT_LIN_MASK	(0x3F << DENALI_CTL9_CASLAT_LIN_SHIFT)
#define DENALI_CTL9_NO_CMD_INIT_SHIFT	(16)
#define DENALI_CTL9_NO_CMD_INIT_MASK	(1 << DENALI_CTL9_NO_CMD_INIT_SHIFT)
#define DENALI_CTL9_TDLL_SHIFT		(0)
#define DENALI_CTL9_TDLL_MASK		(0xFFFF << DENALI_CTL9_TDLL_SHIFT)

#define DENALI_CTL10_TCCD_SHIFT		(24)
#define DENALI_CTL10_TCCD_MASK		(0x1F << DENALI_CTL10_TCCD_SHIFT)
#define DENALI_CTL10_TBSTINT_SHIFT	(16)
#define DENALI_CTL10_TBSTINT_MASK	(0x07 << DENALI_CTL10_TBSTINT_SHIFT)
#define DENALI_CTL10_ADDITIVE_LAT_SHIFT	(8)
#define DENALI_CTL10_ADDITIVE_LAT_MASK	(0x1F << DENALI_CTL10_ADDITIVE_LAT_SHIFT)
#define DENALI_CTL10_WRLAT_SHIFT	(0)
#define DENALI_CTL10_WRLAT_MASK		(0x1F << DENALI_CTL10_WRLAT_SHIFT)

#define DENALI_CTL11_TWTR_SHIFT		(24)
#define DENALI_CTL11_TWTR_MASK		(0xF << DENALI_CTL11_TWTR_SHIFT)
#define DENALI_CTL11_TRAS_MIN_SHIFT	(16)
#define DENALI_CTL11_TRAS_MIN_MASK	(0xFF << DENALI_CTL11_TRAS_MIN_SHIFT)
#define DENALI_CTL11_TRC_SHIFT		(8)
#define DENALI_CTL11_TRC_MASK		(0xFF << DENALI_CTL11_TRC_SHIFT)
#define DENALI_CTL11_TRRD_SHIFT		(0)
#define DENALI_CTL11_TRRD_MASK		(0xFF << DENALI_CTL11_TRRD_SHIFT)

#define DENALI_CTL12_TMRD_SHIFT		(24)
#define DENALI_CTL12_TMRD_MASK		(0x1F << DENALI_CTL12_TMRD_SHIFT)
#define DENALI_CTL12_TRTP_SHIFT		(16)
#define DENALI_CTL12_TRTP_MASK		(0xF << DENALI_CTL12_TRTP_SHIFT)
#define DENALI_CTL12_TFAW_SHIFT		(8)
#define DENALI_CTL12_TFAW_MASK		(0x3F << DENALI_CTL12_TFAW_SHIFT)
#define DENALI_CTL12_TRP_SHIFT		(0)
#define DENALI_CTL12_TRP_MASK		(0x1F << DENALI_CTL12_TRP_SHIFT)

#define DENALI_CTL13_TRAS_MAX_SHIFT	(8)
#define DENALI_CTL13_TRAS_MAX_MASK	(0x1FFFF << DENALI_CTL13_TRAS_MAX_SHIFT)
#define DENALI_CTL13_TMOD_SHIFT		(0)
#define DENALI_CTL13_TMOD_MASK		(0xFF << DENALI_CTL13_TMOD_SHIFT)

#define DENALI_CTL14_TRCD_SHIFT		(24)
#define DENALI_CTL14_TRCD_MASK		(0xFF << DENALI_CTL14_TRCD_SHIFT)
#define DENALI_CTL14_WRITEINTERP_SHIFT	(16)
#define DENALI_CTL14_WRITEINTERP_MASK	(1 << DENALI_CTL14_WRITEINTERP_SHIFT)
#define DENALI_CTL14_TCKESR_SHIFT	(8)
#define DENALI_CTL14_TCKESR_MASK	(0x1F << DENALI_CTL14_TCKESR_SHIFT)
#define DENALI_CTL14_TCKE_SHIFT		(0)
#define DENALI_CTL14_TCKE_MASK		(0x7 << DENALI_CTL14_TCKE_SHIFT)

#define DENALI_CTL15_CONCURRENTAP_SHIFT	(24)
#define DENALI_CTL15_CONCURRENTAP_MASK	(1 << DENALI_CTL15_CONCURRENTAP_SHIFT)
#define DENALI_CTL15_AP_SHIFT		(16)
#define DENALI_CTL15_AP_MASK		(1 << DENALI_CTL15_AP_SHIFT)
#define DENALI_CTL15_TWR_SHIFT		(0)
#define DENALI_CTL15_TWR_MASK		(0x3F << DENALI_CTL15_AP_SHIFT)

#define DENALI_CTL16_TRP_AB_SHIFT	(24)
#define DENALI_CTL16_TRP_AB_MASK	(0x1F << DENALI_CTL16_TRP_AB_SHIFT)
#define DENALI_CTL16_BSTLEN_SHIFT	(16)
#define DENALI_CTL16_BSTLEN_MASK	(0x7 << DENALI_CTL16_BSTLEN_SHIFT)
#define DENALI_CTL16_TDAL_SHIFT		(8)
#define DENALI_CTL16_TDAL_MASK		(0x3F << DENALI_CTL16_TDAL_SHIFT)
#define DENALI_CTL16_TRAS_LOCKOUT_SHIFT	(0)
#define DENALI_CTL16_TRAS_LOCKOUT_MASK	(1 << DENALI_CTL16_TRAS_LOCKOUT_SHIFT)

#define DENALI_CTL17_OPTIMAL_RMODW_EN_SHIFT	(16)
#define DENALI_CTL17_OPTIMAL_RMODW_EN_MASK	(1 << DENALI_CTL17_OPTIMAL_RMODW_EN_SHIFT)
#define DENALI_CTL17_REG_DIMM_ENABLE_SHIFT	(0)
#define DENALI_CTL17_REG_DIMM_ENABLE_MASK	(1 << DENALI_CTL17_REG_DIMM_ENABLE_SHIFT)

#define DENALI_CTL18_TREF_ENABLE_SHIFT	(16)
#define DENALI_CTL18_TREF_ENABLE_MASK	(1 << DENALI_CTL18_TREF_ENABLE_SHIFT)
#define DENALI_CTL18_AREFRESH_SHIFT	(0)
#define DENALI_CTL18_AREFRESH_MASK	(1 << DENALI_CTL18_AREFRESH_SHIFT)

#define DENALI_CTL19_TREF_SHIFT		(16)
#define DENALI_CTL19_TREF_MASK		(0x3FFF << DENALI_CTL19_TREF_SHIFT)
#define DENALI_CTL19_TRFC_SHIFT		(0)
#define DENALI_CTL19_TRFC_MASK		(0x3FF << DENALI_CTL19_TRFC_SHIFT)

#define DENALI_CTL21_TXPDLL_SHIFT	(16)
#define DENALI_CTL21_TXPDLL_MASK	(0xFFFF << DENALI_CTL21_TXPDLL_SHIFT)
#define DENALI_CTL21_TPDEX_SHIFT	(0)
#define DENALI_CTL21_TPDEX_MASK		(0xFFFF << DENALI_CTL21_TPDEX_SHIFT)

#define DENALI_CTL22_TXARDS_SHIFT	(16)
#define DENALI_CTL22_TXARDS_MASK	(0xFFFF << DENALI_CTL22_TXARDS_SHIFT)
#define DENALI_CTL22_TXARD_SHIFT	(0)
#define DENALI_CTL22_TXARD_MASK		(0xFFFF << DENALI_CTL22_TXARD_SHIFT)

#define DENALI_CTL23_TXSNR_SHIFT	(16)
#define DENALI_CTL23_TXSNR_MASK		(0xFFFF << DENALI_CTL23_TXSNR_SHIFT)
#define DENALI_CTL23_TXSR_SHIFT		(0)
#define DENALI_CTL23_TXSR_MASK		(0xFFFF << DENALI_CTL23_TXSR_SHIFT)

#define DENALI_CTL24_ENABLE_QUICK_SREFRESH_SHIFT	(16)
#define DENALI_CTL24_ENABLE_QUICK_SREFRESH_MASK		(1 << DENALI_CTL24_ENABLE_QUICK_SREFRESH_SHIFT)

#define DENALI_CTL25_CKSRX_SHIFT	(16)
#define DENALI_CTL25_CKSRX_MASK		(0xF << DENALI_CTL25_CKSRX_SHIFT)
#define DENALI_CTL25_CKSRE_SHIFT	(8)
#define DENALI_CTL25_CKSRE_MASK		(0xF << DENALI_CTL25_CKSRE_SHIFT)

#define DENALI_CTL32_MR1_DATA_0_SHIFT		(16)
#define DENALI_CTL32_MR1_DATA_0_MASK		(0x7FFF << DENALI_CTL32_MR1_DATA_0_SHIFT)
#define DENALI_CTL32_MR0_DATA_0_SHIFT		(0)
#define DENALI_CTL32_MR0_DATA_0_MASK		(0x7FFF << DENALI_CTL32_MR0_DATA_0_SHIFT)

#define DENALI_CTL33_MRSINGLE_DATA_0_SHIFT	(16)
#define DENALI_CTL33_MRSINGLE_DATA_0_MASK	(0x7FFF << DENALI_CTL33_MRSINGLE_DATA_0_SHIFT)
#define DENALI_CTL33_MR2_DATA_0_SHIFT		(0)
#define DENALI_CTL33_MR2_DATA_0_MASK		(0x7FFF << DENALI_CTL33_MR2_DATA_0_SHIFT)

#define DENALI_CTL38_CTRL_RAW_SHIFT		(24)
#define DENALI_CTL38_CTRL_RAW_MASK		(3 << DENALI_CTL38_CTRL_RAW_SHIFT)

#define DENALI_CTL49_ZQCL_SHIFT			(16)
#define DENALI_CTL49_ZQCL_MASK			(0xFFF << DENALI_CTL49_ZQCL_SHIFT)
#define DENALI_CTL49_ZQINIT_SHIFT		(0)
#define DENALI_CTL49_ZQINIT_MASK		(0xFFF << DENALI_CTL49_ZQINIT_SHIFT)

#define DENALI_CTL50_ZQ_ON_SREF_EXIT_SHIFT	(24)
#define DENALI_CTL50_ZQ_ON_SREF_EXIT_MASK	(3 << DENALI_CTL50_ZQ_ON_SREF_EXIT_SHIFT)
#define DENALI_CTL50_ZQCS_SHIFT			(0)
#define DENALI_CTL50_ZQCS_MASK			(0xFFF << DENALI_CTL50_ZQCS_SHIFT)

#define DENALI_CTL51_ZQ_INTERVAL_SHIFT		(0)
#define DENALI_CTL51_ZQ_INTERVAL_MASK		(0xFFFFFFFF)

#define DENALI_CTL53_COL_DIFF_SHIFT		(24)
#define DENALI_CTL53_COL_DIFF_MASK		(0xF << DENALI_CTL53_COL_DIFF_SHIFT)
#define DENALI_CTL53_ROW_DIFF_SHIFT		(16)
#define DENALI_CTL53_ROW_DIFF_MASK		(0x7 << DENALI_CTL53_ROW_DIFF_SHIFT)
#define DENALI_CTL53_BANK_DIFF_SHIFT		(8)
#define DENALI_CTL53_BANK_DIFF_MASK		(0x3 << DENALI_CTL53_BANK_DIFF_SHIFT)

#define DENALI_CTL54_ADDR_CMP_EN_SHIFT		(24)
#define DENALI_CTL54_ADDR_CMP_EN_MASK		(1 << DENALI_CTL54_ADDR_CMP_EN_SHIFT)
#define DENALI_CTL54_COMMAND_AGE_COUNT_SHIFT	(16)
#define DENALI_CTL54_COMMAND_AGE_COUNT_MASK	(0xFF << DENALI_CTL54_COMMAND_AGE_COUNT_SHIFT)
#define DENALI_CTL54_AGE_COUNT_SHIFT		(8)
#define DENALI_CTL54_AGE_COUNT_MASK		(0xFF << DENALI_CTL54_AGE_COUNT_SHIFT)
#define DENALI_CTL54_APREBIT_SHIFT		(0)
#define DENALI_CTL54_APREBIT_MASK		(0xF << DENALI_CTL54_APREBIT_SHIFT)

#define DENALI_CTL55_RW_SAME_EN_SHIFT		(24)
#define DENALI_CTL55_RW_SAME_EN_MASK 		(1 << DENALI_CTL55_RW_SAME_EN_SHIFT)
#define DENALI_CTL55_PRIORITY_EN_SHIFT		(16)
#define DENALI_CTL55_PRIORITY_EN_MASK 		(1 << DENALI_CTL55_PRIORITY_EN_SHIFT)
#define DENALI_CTL55_PLACEMENT_EN_SHIFT		(8)
#define DENALI_CTL55_PLACEMENT_EN_MASK 		(1 << DENALI_CTL55_PLACEMENT_EN_SHIFT)
#define DENALI_CTL55_BANK_SPLIT_EN_SHIFT	(0)
#define DENALI_CTL55_BANK_SPLIT_EN_MASK		(1 << DENALI_CTL55_BANK_SPLIT_EN_SHIFT)

#define DENALI_CTL56_DISABLE_RW_GROUP_W_BNK_CONFLICT_SHIFT	(24)
#define DENALI_CTL56_DISABLE_RW_GROUP_W_BNK_CONFLICT_MASK	(3 << DENALI_CTL56_DISABLE_RW_GROUP_W_BNK_CONFLICT_SHIFT)
#define DENALI_CTL56_RW_SAME_PAGE_EN_SHIFT			(0)
#define DENALI_CTL56_RW_SAME_PAGE_EN_MASK			(1 << DENALI_CTL56_RW_SAME_PAGE_EN_SHIFT)

#define DENALI_CTL57_INHIBIT_DRAM_CMD_SHIFT		(24)
#define DENALI_CTL57_INHIBIT_DRAM_CMD_MASK		(1 << DENALI_CTL57_INHIBIT_DRAM_CMD_SHIFT)
#define DENALI_CTL57_DISABLE_RD_INTERLEAVE_SHIFT	(16)
#define DENALI_CTL57_DISABLE_RD_INTERLEAVE_MASK		(1 << DENALI_CTL57_DISABLE_RD_INTERLEAVE_SHIFT)
#define DENALI_CTL57_SWAP_EN_SHIFT			(8)
#define DENALI_CTL57_SWAP_EN_MASK			(1 << DENALI_CTL57_SWAP_EN_SHIFT)
#define DENALI_CTL57_NUM_Q_ENTRIES_ACT_DISABLE_SHIFT	(0)
#define DENALI_CTL57_NUM_Q_ENTRIES_ACT_DISABLE_MASK	(0x7 << DENALI_CTL57_NUM_Q_ENTRIES_ACT_DISABLE_SHIFT)

#define DENALI_CTL58_REDUC_SHIFT			(16)
#define DENALI_CTL58_REDUC_MASK				(1 << DENALI_CTL58_REDUC_SHIFT)

#define DENALI_CTL59_CTRLUPD_REQ_SHIFT			(24)
#define DENALI_CTL59_CTRLUPD_REQ_MASK			(1 << DENALI_CTL59_CTRLUPD_REQ_SHIFT)
#define DENALI_CTL59_CONTROLLER_BUSY_SHIFT		(16)
#define DENALI_CTL59_CONTROLLER_BUSY_MASK		(1 << DENALI_CTL59_CONTROLLER_BUSY_SHIFT)
#define DENALI_CTL59_IN_ORDER_ACCEPT_SHIFT		(8)
#define DENALI_CTL59_IN_ORDER_ACCEPT_MASK		(1 << DENALI_CTL59_IN_ORDER_ACCEPT_SHIFT)
#define DENALI_CTL59_Q_FULLNESS_SHIFT			(0)
#define DENALI_CTL59_Q_FULLNESS_MASK			(0x7 << DENALI_CTL59_Q_FULLNESS_SHIFT)

#define DENALI_CTL60_CTRLUPD_REQ_PER_AREF_EN_SHIFT	(0)
#define DENALI_CTL60_CTRLUPD_REQ_PER_AREF_EN_MASK	(1 << DENALI_CTL60_CTRLUPD_REQ_PER_AREF_EN_SHIFT)

#define DENALI_CTL61_INTSTA_INIT_COMPL_MASK	(1 << 8)

#define DENALI_CTL62_INTACK_INIT_COMPL_MASK	(1 << 8)

#define DENALI_CTL70_ODT_EN_SHIFT		(24)
#define DENALI_CTL70_ODT_EN_MASK		(1 << DENALI_CTL70_ODT_EN_SHIFT)
#define DENALI_CTL70_TODTH_WR_SHIFT		(8)
#define DENALI_CTL70_TODTH_WR_MASK		(0xF << DENALI_CTL70_TODTH_WR_SHIFT)
#define DENALI_CTL70_TODTL_2CMD_SHIFT		(0)
#define DENALI_CTL70_TODTL_2CMD_MASK		(0x1F << DENALI_CTL70_TODTL_2CMD_SHIFT)

#define DENALI_CTL73_W2W_SAMECS_DLY_SHIFT	(24)
#define DENALI_CTL73_W2W_SAMECS_DLY_MASK	(0x7 << DENALI_CTL73_W2W_SAMECS_DLY_SHIFT)
#define DENALI_CTL73_W2R_SAMECS_DLY_SHIFT	(16)
#define DENALI_CTL73_W2R_SAMECS_DLY_MASK	(0x7 << DENALI_CTL73_W2R_SAMECS_DLY_SHIFT)
#define DENALI_CTL73_R2W_SAMECS_DLY_SHIFT	(8)
#define DENALI_CTL73_R2W_SAMECS_DLY_MASK	(0x7 << DENALI_CTL73_R2W_SAMECS_DLY_SHIFT)
#define DENALI_CTL73_R2R_SAMECS_DLY_SHIFT	(0)
#define DENALI_CTL73_R2R_SAMECS_DLY_MASK	(0x7 << DENALI_CTL73_R2R_SAMECS_DLY_SHIFT)

#define DENALI_CTL78_WLMRD_SHIFT		(24)
#define DENALI_CTL78_WLMRD_MASK			(0x3F << DENALI_CTL78_WLMRD_SHIFT)
#define DENALI_CTL78_WLDQSEN_SHIFT		(16)
#define DENALI_CTL78_WLDQSEN_MASK		(0x3F << DENALI_CTL78_WLDQSEN_SHIFT)

#define DENALI_CTL81_WRLVL_DELAY_1_SHIFT	(16)
#define DENALI_CTL81_WRLVL_DELAY_1_MASK		(0xFFFF << DENALI_CTL81_WRLVL_DELAY_1_SHIFT)
#define DENALI_CTL81_WRLVL_DELAY_0_SHIFT	(0)
#define DENALI_CTL81_WRLVL_DELAY_0_MASK		(0xFFFF << DENALI_CTL81_WRLVL_DELAY_0_SHIFT)

#define DENALI_CTL82_WRLVL_DELAY_3_SHIFT	(16)
#define DENALI_CTL82_WRLVL_DELAY_3_MASK		(0xFFFF << DENALI_CTL82_WRLVL_DELAY_3_SHIFT)
#define DENALI_CTL82_WRLVL_DELAY_2_SHIFT	(0)
#define DENALI_CTL82_WRLVL_DELAY_2_MASK		(0xFFFF << DENALI_CTL82_WRLVL_DELAY_2_SHIFT)

#define DENALI_CTL83_RDLVL_GATE_REQ_SHIFT	(24)
#define DENALI_CTL83_RDLVL_GATE_REQ_MASK	(1 << DENALI_CTL83_RDLVL_GATE_REQ_SHIFT)
#define DENALI_CTL83_RDLVL_REQ_SHIFT		(16)
#define DENALI_CTL83_RDLVL_REQ_MASK		(1 << DENALI_CTL83_RDLVL_REQ_SHIFT)
#define DENALI_CTL83_WRLVL_DELAY_4_SHIFT	(0)
#define DENALI_CTL83_WRLVL_DELAY_4_MASK		(0xFFFF << DENALI_CTL83_WRLVL_DELAY_4_SHIFT)

#define DENALI_CTL88_RDLVL_GATE_DELAY_0_SHIFT	(16)
#define DENALI_CTL88_RDLVL_GATE_DELAY_0_MASK	(0xFFFF << DENALI_CTL88_RDLVL_GATE_DELAY_0_SHIFT)
#define DENALI_CTL88_RDLVL_DELAY_0_SHIFT	(0)
#define DENALI_CTL88_RDLVL_DELAY_0_MASK		(0xFFFF << DENALI_CTL88_RDLVL_DELAY_0_SHIFT)

#define DENALI_CTL91_RDLVL_DELAY_1_SHIFT	(8)
#define DENALI_CTL91_RDLVL_DELAY_1_MASK		(0xFFFF << DENALI_CTL91_RDLVL_DELAY_1_SHIFT)
#define DENALI_CTL91_RDLVL_OFFSET_DIR_1_SHIFT	(0)
#define DENALI_CTL91_RDLVL_OFFSET_DIR_1_MASK	(1 << DENALI_CTL91_RDLVL_OFFSET_DIR_1_SHIFT)

#define DENALI_CTL95_RDLVL_GATE_DELAY_2_SHIFT	(16)
#define DENALI_CTL95_RDLVL_GATE_DELAY_2_MASK	(0xFFFF << DENALI_CTL95_RDLVL_GATE_DELAY_2_SHIFT)
#define DENALI_CTL95_RDLVL_DELAY_2_SHIFT	(0)
#define DENALI_CTL95_RDLVL_DELAY_2_MASK		(0xFFFF << DENALI_CTL95_RDLVL_DELAY_2_SHIFT)

#define DENALI_CTL98_RDLVL_DELAY_3_SHIFT	(8)
#define DENALI_CTL98_RDLVL_DELAY_3_MASK		(0xFFFF << DENALI_CTL98_RDLVL_DELAY_3_SHIFT)
#define DENALI_CTL98_RDLVL_OFFSET_DIR_3_SHIFT	(0)
#define DENALI_CTL98_RDLVL_OFFSET_DIR_3_MASK	(1 << DENALI_CTL98_RDLVL_OFFSET_DIR_3_SHIFT)

#define DENALI_CTL99_RDLVL_BEGIN_DELAY_4_SHIFT	(16)
#define DENALI_CTL99_RDLVL_BEGIN_DELAY_4_MASK	(0xFFFF << DENALI_CTL99_RDLVL_BEGIN_DELAY_4_SHIFT)
#define DENALI_CTL99_RDLVL_GATE_DELAY_3_SHIFT	(0)
#define DENALI_CTL99_RDLVL_GATE_DELAY_3_MASK	(0xFFFF << DENALI_CTL99_RDLVL_GATE_DELAY_3_SHIFT)

#define DENALI_CTL102_RDLVL_GATE_DELAY_4_SHIFT	(16)
#define DENALI_CTL102_RDLVL_DELAY_4_SHIFT	(0)

#define DENALI_CTL103_AXI1_ALL_STROBES_USED_ENABLE_SHIFT	(24)
#define DENALI_CTL103_AXI0_W_PRIORITY_SHIFT			(16)
#define DENALI_CTL103_AXI0_R_PRIORITY_SHIFT			(8)
#define DENALI_CTL103_AXI0_ALL_STROBES_USED_ENABLE_SHIFT	(0)

#define DENALI_CTL104_AXI2_R_PRIORITY_SHIFT			(24)
#define DENALI_CTL104_AXI2_ALL_STROBES_USED_ENABLE_SHIFT	(16)
#define DENALI_CTL104_AXI1_W_PRIORITY_SHIFT			(8)
#define DENALI_CTL104_AXI1_R_PRIORITY_SHIFT			(0)

#define DENALI_CTL105_AXI3_W_PRIORITY_SHIFT			(24)
#define DENALI_CTL105_AXI3_R_PRIORITY_SHIFT			(16)
#define DENALI_CTL105_AXI3_ALL_STROBES_USED_ENABLE_SHIFT	(8)
#define DENALI_CTL105_AXI2_W_PRIORITY_SHIFT			(0)

#define DENALI_CTL106_WEIGHTED_ROUND_ROBIN_LATENCY_CONTROL_SHIFT	(24)
#define DENALI_CTL106_AXI4_W_PRIORITY_SHIFT				(16)
#define DENALI_CTL106_AXI4_R_PRIORITY_SHIFT				(8)
#define DENALI_CTL106_AXI4_ALL_STROBES_USED_ENABLE_SHIFT		(0)

#define DENALI_CTL107_AXI0_PRIORITY1_RELATIVE_PRIORITY_SHIFT	(24)
#define DENALI_CTL107_AXI0_PRIORITY0_RELATIVE_PRIORITY_SHIFT	(16)
#define DENALI_CTL107_WRR_PARAM_VALUE_ERR_SHIFT			(8)
#define DENALI_CTL107_WEIGHTED_ROUND_ROBIN_WEIGHT_SHARING_SHIFT	(0)

#define DENALI_CTL108_AXI0_PORT_ORDERING_SHIFT			(16)
#define DENALI_CTL108_AXI0_PRIORITY3_RELATIVE_PRIORITY_SHIFT	(8)
#define DENALI_CTL108_AXI0_PRIORITY2_RELATIVE_PRIORITY_SHIFT	(0)

#define DENALI_CTL109_AXI1_PRIORITY1_RELATIVE_PRIORITY_SHIFT	(24)
#define DENALI_CTL109_AXI1_PRIORITY0_RELATIVE_PRIORITY_SHIFT	(16)
#define DENALI_CTL109_AXI0_PRIORITY_RELAX_SHIFT			(0)

#define DENALI_CTL110_AXI1_PORT_ORDERING_SHIFT			(16)
#define DENALI_CTL110_AXI1_PRIORITY3_RELATIVE_PRIORITY_SHIFT	(8)
#define DENALI_CTL110_AXI1_PRIORITY2_RELATIVE_PRIORITY_SHIFT	(0)

#define DENALI_CTL111_AXI2_PRIORITY1_RELATIVE_PRIORITY_SHIFT	(24)
#define DENALI_CTL111_AXI2_PRIORITY0_RELATIVE_PRIORITY_SHIFT	(16)
#define DENALI_CTL111_AXI1_PRIORITY_RELAX_SHIFT			(0)

#define DENALI_CTL112_AXI2_PORT_ORDERING_SHIFT			(16)
#define DENALI_CTL112_AXI2_PRIORITY3_RELATIVE_PRIORITY_SHIFT	(8)
#define DENALI_CTL112_AXI2_PRIORITY2_RELATIVE_PRIORITY_SHIFT	(0)

#define DENALI_CTL113_AXI3_PRIORITY1_RELATIVE_PRIORITY_SHIFT	(24)
#define DENALI_CTL113_AXI3_PRIORITY0_RELATIVE_PRIORITY_SHIFT	(16)
#define DENALI_CTL113_AXI2_PRIORITY_RELAX_SHIFT			(0)

#define DENALI_CTL114_AXI3_PORT_ORDERING_SHIFT			(16)
#define DENALI_CTL114_AXI3_PRIORITY3_RELATIVE_PRIORITY_SHIFT	(8)
#define DENALI_CTL114_AXI3_PRIORITY2_RELATIVE_PRIORITY_SHIFT	(0)

#define DENALI_CTL115_AXI4_PRIORITY1_RELATIVE_PRIORITY_SHIFT	(24)
#define DENALI_CTL115_AXI4_PRIORITY0_RELATIVE_PRIORITY_SHIFT	(16)
#define DENALI_CTL115_AXI3_PRIORITY_RELAX_SHIFT			(0)

#define DENALI_CTL116_AXI4_PORT_ORDERING_SHIFT			(16)
#define DENALI_CTL116_AXI4_PRIORITY3_RELATIVE_PRIORITY_SHIFT	(8)
#define DENALI_CTL116_AXI4_PRIORITY2_RELATIVE_PRIORITY_SHIFT	(0)

#define DENALI_CTL117_MEM_RST_VALID_SHIFT			(24)
#define DENALI_CTL117_CKE_STATUS_SHIFT				(16)
#define DENALI_CTL117_AXI4_PRIORITY_RELAX_SHIFT			(0)

#define DENALI_CTL119_DRAM_CLK_DISABLE_SHIFT			(24)
#define DENALI_CTL119_TDFI_RDDATA_EN_SHIFT			(16)
#define DENALI_CTL119_TDFI_PHY_RDLAT_SHIFT			(8)
#define DENALI_CTL119_UPDATE_ERROR_STATUS_SHIFT			(0)

#define DENALI_CTL120_TDFI_CTRLUPD_MAX_SHIFT			(8)
#define DENALI_CTL120_TDFI_CTRLUPD_MIN_SHIFT			(0)

#define DENALI_CTL121_TDFI_PHYUPD_TYPE1_SHIFT			(16)
#define DENALI_CTL121_TDFI_PHYUPD_TYPE0_SHIFT			(0)

#define DENALI_CTL122_TDFI_PHYUPD_TYPE3_SHIFT			(16)
#define DENALI_CTL122_TDFI_PHYUPD_TYPE2_SHIFT			(0)

#define DENALI_CTL123_TDFI_PHYUPD_RESP_SHIFT			(0)

#define DENALI_CTL124_TDFI_CTRLUPD_INTERVAL_SHIFT		(0)

#define DENALI_CTL125_TDFI_DRAM_CLK_DISABLE_SHIFT		(24)
#define DENALI_CTL125_TDFI_CTRL_DELAY_SHIFT			(16)
#define DENALI_CTL125_WRLAT_ADJ_SHIFT				(8)
#define DENALI_CTL125_RDLAT_ADJ_SHIFT				(0)
#define SRT_NX4000_DDR_CTRL_CTL125_TDFI_DRAM_CLK_DISABLE	DENALI_CTL125_TDFI_DRAM_CLK_DISABLE_SHIFT
#define SRT_NX4000_DDR_CTRL_CTL125_TDFI_CTRL_DELAY		DENALI_CTL125_TDFI_CTRL_DELAY_SHIFT
#define SRT_NX4000_DDR_CTRL_CTL125_WRLAT_ADJ			DENALI_CTL125_WRLAT_ADJ_SHIFT
#define SRT_NX4000_DDR_CTRL_CTL125_RDLAT_ADJ			DENALI_CTL125_RDLAT_ADJ_SHIFT

#define DENALI_CTL126_TDFI_WRLVL_WW_SHIFT			(16)
#define DENALI_CTL126_TDFI_WRLVL_EN_SHIFT			(8)
#define DENALI_CTL126_TDFI_DRAM_CLK_ENABLE_SHIFT		(0)

#define DENALI_CTL129_TDFI_WRLVL_RESPLAT_SHIFT			(24)
#define DENALI_CTL129_TDFI_WRLVL_DLL_SHIFT			(16)
#define DENALI_CTL129_DFI_WRLVL_MAX_DELAY_SHIFT			(0)

#define DENALI_CTL130_TDFI_RDLVL_LOAD_SHIFT			(24)
#define DENALI_CTL130_TDFI_RDLVL_DLL_SHIFT			(16)
#define DENALI_CTL130_TDFI_RDLVL_EN_SHIFT			(8)
#define DENALI_CTL130_TDFI_WRLVL_LOAD_SHIFT			(0)

#define DENALI_CTL131_RDLVL_MAX_DELAY_SHIFT			(8)
#define DENALI_CTL131_TDFI_RDLVL_RESPLAT_SHIFT			(0)

#define DENALI_CTL132_TDFI_RDLVL_RR_SHIFT			(16)
#define DENALI_CTL132_RDLVL_GATE_MAX_DELAY_SHIFT		(0)

#define DENALI_CTL133_TDFI_RDLVL_RESP_SHIFT			(0)

#define DENALI_CTL142_TDFI_PHY_WRDATA_SHIFT			(0)

#define DENALI_CTL150_RESERVED3_SHIFT				(24)
#define DENALI_CTL150_AXI4_WRCMD_PROC_FIFO_LOG2_DEPTH_SHIFT	(16)
#define DENALI_CTL150_AXI4_WRFIFO_LOG2_DEPTH_SHIFT		(8)
#define DENALI_CTL150_AXI4_RDFIFO_LOG2_DEPTH_SHIFT		(0)

#define DENALI_CTRL152_ECC_EN_SHIFT				(0)
#define SRT_NX4000_DDR_CTRL_CTL152_ECC_EN			DENALI_CTRL152_ECC_EN_SHIFT

#define DENALI_CTL160_INT_MASK_SHIFT				(0)
#define SRT_NX4000_DDR_CTRL_CTL160_INT_MASK			DENALI_CTL160_INT_MASK_SHIFT

#endif /* _NETX4000_DDR_H_ */
